# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - xbi-as-access-manager-scim-d-we-005

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io//
        username: ${{ secrets.AzureAppService_ContainerUsername_bbf5c00f53534f909055e29147f59519 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_02edf7aa6b9c427b8dcedb4c8da0e069 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io//${{ secrets.AzureAppService_ContainerUsername_bbf5c00f53534f909055e29147f59519 }}/keystone-scim/keystone:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'xbi-as-access-manager-scim-d-we-005'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ff6c270010e64a218128d68f31c7a840 }}
        images: 'ghcr.io//${{ secrets.AzureAppService_ContainerUsername_bbf5c00f53534f909055e29147f59519 }}/keystone-scim/keystone:${{ github.sha }}'